"""Add officer address intermediary tables and extend entity types

Revision ID: 6fc5383b6719
Revises: 002
Create Date: 2026-01-15 14:21:05.051596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc5383b6719'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add new values to EntityType enum
    op.execute("ALTER TYPE entitytype ADD VALUE IF NOT EXISTS 'OFFICER'")
    op.execute("ALTER TYPE entitytype ADD VALUE IF NOT EXISTS 'ADDRESS'")
    op.execute("ALTER TYPE entitytype ADD VALUE IF NOT EXISTS 'INTERMEDIARY'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_address', sa.Text(), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_address'))
    )
    op.create_index(op.f('ix_address_city'), 'address', ['city'], unique=False)
    op.create_index(op.f('ix_address_id'), 'address', ['id'], unique=False)
    op.create_index(op.f('ix_address_province'), 'address', ['province'], unique=False)
    op.create_table('intermediary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('intermediary_type', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intermediary'))
    )
    op.create_index(op.f('ix_intermediary_country'), 'intermediary', ['country'], unique=False)
    op.create_index(op.f('ix_intermediary_id'), 'intermediary', ['id'], unique=False)
    op.create_index(op.f('ix_intermediary_name'), 'intermediary', ['name'], unique=False)
    op.create_table('officer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id_number_masked', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_officer')),
    sa.UniqueConstraint('id_number_masked', name=op.f('uq_officer_id_number_masked'))
    )
    op.create_index(op.f('ix_officer_id'), 'officer', ['id'], unique=False)
    op.create_index(op.f('ix_officer_name'), 'officer', ['name'], unique=False)
    op.drop_index(op.f('ix_beneficial_owner_id_number_masked'), table_name='beneficial_owner')
    op.drop_index(op.f('ix_beneficial_owner_name_trgm'), table_name='beneficial_owner', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_unique_constraint(op.f('uq_beneficial_owner_id_number_masked'), 'beneficial_owner', ['id_number_masked'])
    op.drop_index(op.f('ix_group_name_trgm'), table_name='group', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_group_definition_rule_set_is_active'), table_name='group_definition_rule_set')
    op.drop_index(op.f('ix_group_membership_composite'), table_name='group_membership')
    op.drop_index(op.f('ix_relationship_composite_from'), table_name='relationship')
    op.drop_index(op.f('ix_relationship_composite_to'), table_name='relationship')
    op.drop_index(op.f('ix_taxpayer_name_trgm'), table_name='taxpayer', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_taxpayer_yearly_financial_composite'), table_name='taxpayer_yearly_financial')
    op.drop_index(op.f('ix_taxpayer_yearly_ratio_composite'), table_name='taxpayer_yearly_ratio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_taxpayer_yearly_ratio_composite'), 'taxpayer_yearly_ratio', ['taxpayer_id', 'tax_year', 'ratio_code'], unique=False)
    op.create_index(op.f('ix_taxpayer_yearly_financial_composite'), 'taxpayer_yearly_financial', ['taxpayer_id', 'tax_year'], unique=False)
    op.create_index(op.f('ix_taxpayer_name_trgm'), 'taxpayer', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_relationship_composite_to'), 'relationship', ['to_entity_type', 'to_entity_id'], unique=False)
    op.create_index(op.f('ix_relationship_composite_from'), 'relationship', ['from_entity_type', 'from_entity_id'], unique=False)
    op.create_index(op.f('ix_group_membership_composite'), 'group_membership', ['group_id', 'taxpayer_id'], unique=False)
    op.create_index(op.f('ix_group_definition_rule_set_is_active'), 'group_definition_rule_set', ['is_active'], unique=False)
    op.create_index(op.f('ix_group_name_trgm'), 'group', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint(op.f('uq_beneficial_owner_id_number_masked'), 'beneficial_owner', type_='unique')
    op.create_index(op.f('ix_beneficial_owner_name_trgm'), 'beneficial_owner', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_beneficial_owner_id_number_masked'), 'beneficial_owner', ['id_number_masked'], unique=True)
    op.drop_index(op.f('ix_officer_name'), table_name='officer')
    op.drop_index(op.f('ix_officer_id'), table_name='officer')
    op.drop_table('officer')
    op.drop_index(op.f('ix_intermediary_name'), table_name='intermediary')
    op.drop_index(op.f('ix_intermediary_id'), table_name='intermediary')
    op.drop_index(op.f('ix_intermediary_country'), table_name='intermediary')
    op.drop_table('intermediary')
    op.drop_index(op.f('ix_address_province'), table_name='address')
    op.drop_index(op.f('ix_address_id'), table_name='address')
    op.drop_index(op.f('ix_address_city'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
